// Code generated by protoc-gen-go. DO NOT EDIT.
// source: case.proto

package _case

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Case struct {
	CaseID               int32    `protobuf:"varint,1,opt,name=caseID,proto3" json:"caseID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Case) Reset()         { *m = Case{} }
func (m *Case) String() string { return proto.CompactTextString(m) }
func (*Case) ProtoMessage()    {}
func (*Case) Descriptor() ([]byte, []int) {
	return fileDescriptor_case_79631fd744df12ec, []int{0}
}
func (m *Case) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Case.Unmarshal(m, b)
}
func (m *Case) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Case.Marshal(b, m, deterministic)
}
func (dst *Case) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Case.Merge(dst, src)
}
func (m *Case) XXX_Size() int {
	return xxx_messageInfo_Case.Size(m)
}
func (m *Case) XXX_DiscardUnknown() {
	xxx_messageInfo_Case.DiscardUnknown(m)
}

var xxx_messageInfo_Case proto.InternalMessageInfo

func (m *Case) GetCaseID() int32 {
	if m != nil {
		return m.CaseID
	}
	return 0
}

type Response struct {
	Status               bool     `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_case_79631fd744df12ec, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*Case)(nil), "case.Case")
	proto.RegisterType((*Response)(nil), "case.Response")
}

func init() { proto.RegisterFile("case.proto", fileDescriptor_case_79631fd744df12ec) }

var fileDescriptor_case_79631fd744df12ec = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4e, 0x2c, 0x4e,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xe4, 0xb8, 0x58, 0x9c, 0x13,
	0x8b, 0x53, 0x85, 0xc4, 0xb8, 0xd8, 0x40, 0x7c, 0x4f, 0x17, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6,
	0x20, 0x28, 0x4f, 0x49, 0x89, 0x8b, 0x23, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0x0f, 0xa2, 0x26, 0xb8,
	0x24, 0xb1, 0xa4, 0xb4, 0x18, 0xac, 0x86, 0x23, 0x08, 0xca, 0x33, 0x0a, 0xe3, 0x62, 0x73, 0x2c,
	0x2e, 0xce, 0x4c, 0xcf, 0x13, 0x52, 0x81, 0xb3, 0xb8, 0xf4, 0xc0, 0x56, 0x81, 0xcc, 0x96, 0xe2,
	0x83, 0xb0, 0xe1, 0xe6, 0xa8, 0x71, 0x71, 0x84, 0xe6, 0x11, 0x56, 0x97, 0xc4, 0x06, 0x76, 0xa8,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xd0, 0xd9, 0xc3, 0xb6, 0x00, 0x00, 0x00,
}
