// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/case.proto

package protos // import "github.com/Banana-no-ana/support-ticket-tycoon/backend/protos"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Case struct {
	CaseID               int32        `protobuf:"varint,1,opt,name=caseID,proto3" json:"caseID,omitempty"`
	Status               string       `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Assignee             int32        `protobuf:"varint,3,opt,name=Assignee,proto3" json:"Assignee,omitempty"`
	CustomerID           int32        `protobuf:"varint,4,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	CurrentStage         int32        `protobuf:"varint,5,opt,name=CurrentStage,proto3" json:"CurrentStage,omitempty"`
	CaseStages           []*CaseStage `protobuf:"bytes,6,rep,name=CaseStages,proto3" json:"CaseStages,omitempty"`
	CustomerSentiment    int32        `protobuf:"varint,7,opt,name=CustomerSentiment,proto3" json:"CustomerSentiment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Case) Reset()         { *m = Case{} }
func (m *Case) String() string { return proto.CompactTextString(m) }
func (*Case) ProtoMessage()    {}
func (*Case) Descriptor() ([]byte, []int) {
	return fileDescriptor_case_052caafca52a7699, []int{0}
}
func (m *Case) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Case.Unmarshal(m, b)
}
func (m *Case) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Case.Marshal(b, m, deterministic)
}
func (dst *Case) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Case.Merge(dst, src)
}
func (m *Case) XXX_Size() int {
	return xxx_messageInfo_Case.Size(m)
}
func (m *Case) XXX_DiscardUnknown() {
	xxx_messageInfo_Case.DiscardUnknown(m)
}

var xxx_messageInfo_Case proto.InternalMessageInfo

func (m *Case) GetCaseID() int32 {
	if m != nil {
		return m.CaseID
	}
	return 0
}

func (m *Case) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Case) GetAssignee() int32 {
	if m != nil {
		return m.Assignee
	}
	return 0
}

func (m *Case) GetCustomerID() int32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *Case) GetCurrentStage() int32 {
	if m != nil {
		return m.CurrentStage
	}
	return 0
}

func (m *Case) GetCaseStages() []*CaseStage {
	if m != nil {
		return m.CaseStages
	}
	return nil
}

func (m *Case) GetCustomerSentiment() int32 {
	if m != nil {
		return m.CustomerSentiment
	}
	return 0
}

type CaseStage struct {
	StageID              int32    `protobuf:"varint,1,opt,name=StageID,proto3" json:"StageID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Difficulty           int32    `protobuf:"varint,4,opt,name=Difficulty,proto3" json:"Difficulty,omitempty"`
	Totalwork            int32    `protobuf:"varint,5,opt,name=Totalwork,proto3" json:"Totalwork,omitempty"`
	Completedwork        int32    `protobuf:"varint,6,opt,name=Completedwork,proto3" json:"Completedwork,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaseStage) Reset()         { *m = CaseStage{} }
func (m *CaseStage) String() string { return proto.CompactTextString(m) }
func (*CaseStage) ProtoMessage()    {}
func (*CaseStage) Descriptor() ([]byte, []int) {
	return fileDescriptor_case_052caafca52a7699, []int{1}
}
func (m *CaseStage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaseStage.Unmarshal(m, b)
}
func (m *CaseStage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaseStage.Marshal(b, m, deterministic)
}
func (dst *CaseStage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaseStage.Merge(dst, src)
}
func (m *CaseStage) XXX_Size() int {
	return xxx_messageInfo_CaseStage.Size(m)
}
func (m *CaseStage) XXX_DiscardUnknown() {
	xxx_messageInfo_CaseStage.DiscardUnknown(m)
}

var xxx_messageInfo_CaseStage proto.InternalMessageInfo

func (m *CaseStage) GetStageID() int32 {
	if m != nil {
		return m.StageID
	}
	return 0
}

func (m *CaseStage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CaseStage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CaseStage) GetDifficulty() int32 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

func (m *CaseStage) GetTotalwork() int32 {
	if m != nil {
		return m.Totalwork
	}
	return 0
}

func (m *CaseStage) GetCompletedwork() int32 {
	if m != nil {
		return m.Completedwork
	}
	return 0
}

func init() {
	proto.RegisterType((*Case)(nil), "case.Case")
	proto.RegisterType((*CaseStage)(nil), "case.CaseStage")
}

func init() { proto.RegisterFile("protos/case.proto", fileDescriptor_case_052caafca52a7699) }

var fileDescriptor_case_052caafca52a7699 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0x53, 0x29, 0x45, 0x46, 0x8d, 0x61, 0x0f, 0x66, 0x63, 0x0c, 0x21, 0xc4, 0x03, 0x07,
	0x4b, 0x13, 0x3d, 0x1b, 0x23, 0xe5, 0xc2, 0x15, 0x38, 0x79, 0x5b, 0xca, 0x80, 0x0d, 0x74, 0xb7,
	0xe9, 0xce, 0xc6, 0xf0, 0xc3, 0xfc, 0x69, 0xde, 0x4d, 0xc7, 0x52, 0x68, 0x3c, 0xf5, 0xbd, 0x6f,
	0xdf, 0xb6, 0xf3, 0x26, 0x85, 0x5e, 0x5e, 0x18, 0x32, 0x36, 0x4a, 0x94, 0xc5, 0x31, 0x6b, 0xe1,
	0x97, 0x7a, 0xf8, 0xe3, 0x81, 0x1f, 0x2b, 0x8b, 0xe2, 0x0e, 0x82, 0x12, 0xcc, 0xa6, 0xd2, 0x1b,
	0x78, 0xa3, 0xf6, 0xbc, 0x72, 0x25, 0x5f, 0x90, 0x22, 0x67, 0xe5, 0xc5, 0xc0, 0x1b, 0x75, 0xe7,
	0x95, 0x13, 0xf7, 0x70, 0xf9, 0x6e, 0x6d, 0xba, 0xd5, 0x88, 0xb2, 0xc5, 0x37, 0x6a, 0x2f, 0xfa,
	0x00, 0xb1, 0xb3, 0x64, 0x32, 0x2c, 0x66, 0x53, 0xe9, 0xf3, 0xe9, 0x19, 0x11, 0x43, 0xb8, 0x8e,
	0x5d, 0x51, 0xa0, 0xa6, 0x05, 0xa9, 0x2d, 0xca, 0x36, 0x27, 0x1a, 0x4c, 0x44, 0x00, 0xe5, 0x5c,
	0x6c, 0xac, 0x0c, 0x06, 0xad, 0xd1, 0xd5, 0xf3, 0xed, 0x98, 0xe7, 0xaf, 0xf9, 0xfc, 0x2c, 0x22,
	0x9e, 0xa0, 0x77, 0xfc, 0xc4, 0x02, 0x35, 0xa5, 0x19, 0x6a, 0x92, 0x1d, 0x7e, 0xf3, 0xff, 0x83,
	0xe1, 0xb7, 0x07, 0xdd, 0xfa, 0xb2, 0x90, 0xd0, 0x61, 0x51, 0xb7, 0x3f, 0x5a, 0x21, 0xc0, 0x5f,
	0x1e, 0x72, 0xac, 0xca, 0xb3, 0x3e, 0x5b, 0x49, 0xab, 0xb1, 0x92, 0x3e, 0xc0, 0x34, 0xdd, 0x6c,
	0xd2, 0xc4, 0xed, 0xe9, 0x70, 0xac, 0x7d, 0x22, 0xe2, 0x01, 0xba, 0x4b, 0x43, 0x6a, 0xff, 0x65,
	0x8a, 0x5d, 0xd5, 0xf9, 0x04, 0xc4, 0x23, 0xdc, 0xc4, 0x26, 0xcb, 0xf7, 0x48, 0xb8, 0xe6, 0x44,
	0xc0, 0x89, 0x26, 0x9c, 0xbc, 0x7d, 0xbc, 0x6e, 0x53, 0xfa, 0x74, 0xab, 0x71, 0x62, 0xb2, 0x68,
	0xa2, 0xb4, 0xd2, 0x2a, 0xd4, 0x26, 0x54, 0x5a, 0x45, 0xd6, 0xe5, 0xb9, 0x29, 0x28, 0xa4, 0x34,
	0xd9, 0x21, 0x85, 0x74, 0x48, 0x8c, 0xd1, 0xd1, 0x4a, 0x25, 0x3b, 0xd4, 0xeb, 0xe8, 0xef, 0x0f,
	0x58, 0x05, 0xfc, 0x7c, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x54, 0x51, 0x6d, 0x1e, 0x12, 0x02,
	0x00, 0x00,
}
