// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/case.proto

package protos // import "github.com/Banana-no-ana/support-ticket-tycoon/backend/protos"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Case struct {
	CaseID               int32    `protobuf:"varint,1,opt,name=caseID,proto3" json:"caseID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Case) Reset()         { *m = Case{} }
func (m *Case) String() string { return proto.CompactTextString(m) }
func (*Case) ProtoMessage()    {}
func (*Case) Descriptor() ([]byte, []int) {
	return fileDescriptor_case_78bb15b4217de220, []int{0}
}
func (m *Case) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Case.Unmarshal(m, b)
}
func (m *Case) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Case.Marshal(b, m, deterministic)
}
func (dst *Case) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Case.Merge(dst, src)
}
func (m *Case) XXX_Size() int {
	return xxx_messageInfo_Case.Size(m)
}
func (m *Case) XXX_DiscardUnknown() {
	xxx_messageInfo_Case.DiscardUnknown(m)
}

var xxx_messageInfo_Case proto.InternalMessageInfo

func (m *Case) GetCaseID() int32 {
	if m != nil {
		return m.CaseID
	}
	return 0
}

type CaseProgress struct {
	CurrentStage         int32        `protobuf:"varint,1,opt,name=currentStage,proto3" json:"currentStage,omitempty"`
	Stage                []*CaseStage `protobuf:"bytes,2,rep,name=Stage,proto3" json:"Stage,omitempty"`
	Status               string       `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CaseProgress) Reset()         { *m = CaseProgress{} }
func (m *CaseProgress) String() string { return proto.CompactTextString(m) }
func (*CaseProgress) ProtoMessage()    {}
func (*CaseProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_case_78bb15b4217de220, []int{1}
}
func (m *CaseProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaseProgress.Unmarshal(m, b)
}
func (m *CaseProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaseProgress.Marshal(b, m, deterministic)
}
func (dst *CaseProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaseProgress.Merge(dst, src)
}
func (m *CaseProgress) XXX_Size() int {
	return xxx_messageInfo_CaseProgress.Size(m)
}
func (m *CaseProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_CaseProgress.DiscardUnknown(m)
}

var xxx_messageInfo_CaseProgress proto.InternalMessageInfo

func (m *CaseProgress) GetCurrentStage() int32 {
	if m != nil {
		return m.CurrentStage
	}
	return 0
}

func (m *CaseProgress) GetStage() []*CaseStage {
	if m != nil {
		return m.Stage
	}
	return nil
}

func (m *CaseProgress) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type CaseStage struct {
	StageID              int32    `protobuf:"varint,1,opt,name=StageID,proto3" json:"StageID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Difficulty           int32    `protobuf:"varint,4,opt,name=Difficulty,proto3" json:"Difficulty,omitempty"`
	Totalwork            int32    `protobuf:"varint,5,opt,name=Totalwork,proto3" json:"Totalwork,omitempty"`
	Completedwork        int32    `protobuf:"varint,6,opt,name=Completedwork,proto3" json:"Completedwork,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaseStage) Reset()         { *m = CaseStage{} }
func (m *CaseStage) String() string { return proto.CompactTextString(m) }
func (*CaseStage) ProtoMessage()    {}
func (*CaseStage) Descriptor() ([]byte, []int) {
	return fileDescriptor_case_78bb15b4217de220, []int{2}
}
func (m *CaseStage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaseStage.Unmarshal(m, b)
}
func (m *CaseStage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaseStage.Marshal(b, m, deterministic)
}
func (dst *CaseStage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaseStage.Merge(dst, src)
}
func (m *CaseStage) XXX_Size() int {
	return xxx_messageInfo_CaseStage.Size(m)
}
func (m *CaseStage) XXX_DiscardUnknown() {
	xxx_messageInfo_CaseStage.DiscardUnknown(m)
}

var xxx_messageInfo_CaseStage proto.InternalMessageInfo

func (m *CaseStage) GetStageID() int32 {
	if m != nil {
		return m.StageID
	}
	return 0
}

func (m *CaseStage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CaseStage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CaseStage) GetDifficulty() int32 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

func (m *CaseStage) GetTotalwork() int32 {
	if m != nil {
		return m.Totalwork
	}
	return 0
}

func (m *CaseStage) GetCompletedwork() int32 {
	if m != nil {
		return m.Completedwork
	}
	return 0
}

func init() {
	proto.RegisterType((*Case)(nil), "case.Case")
	proto.RegisterType((*CaseProgress)(nil), "case.CaseProgress")
	proto.RegisterType((*CaseStage)(nil), "case.CaseStage")
}

func init() { proto.RegisterFile("protos/case.proto", fileDescriptor_case_78bb15b4217de220) }

var fileDescriptor_case_78bb15b4217de220 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4f, 0x4f, 0x83, 0x30,
	0x1c, 0x0d, 0x0e, 0x30, 0xfc, 0x9c, 0x31, 0xf6, 0x60, 0x38, 0x98, 0x85, 0x10, 0x4d, 0xb8, 0x00,
	0x89, 0x9e, 0x8d, 0xc9, 0xb6, 0x8b, 0x37, 0xc3, 0x76, 0xf2, 0x56, 0xba, 0x0e, 0x09, 0xac, 0xc5,
	0xf6, 0x47, 0x0c, 0x1f, 0xcc, 0xef, 0x67, 0x5a, 0x70, 0xba, 0x83, 0xa7, 0xbe, 0x7f, 0x7d, 0xaf,
	0x49, 0xe1, 0xba, 0x53, 0x12, 0xa5, 0xce, 0x19, 0xd5, 0x3c, 0xb3, 0x98, 0xb8, 0x06, 0xc7, 0x0b,
	0x70, 0x57, 0x54, 0x73, 0x72, 0x03, 0xbe, 0xe1, 0x2f, 0xeb, 0xd0, 0x89, 0x9c, 0xc4, 0x2b, 0x26,
	0x16, 0x7f, 0xc0, 0xdc, 0xf8, 0xaf, 0x4a, 0x56, 0x8a, 0x6b, 0x4d, 0x62, 0x98, 0xb3, 0x5e, 0x29,
	0x2e, 0x70, 0x83, 0xb4, 0xe2, 0x53, 0xfa, 0x44, 0x23, 0xf7, 0xe0, 0x8d, 0xe6, 0x59, 0x34, 0x4b,
	0x2e, 0x1e, 0xae, 0x32, 0xbb, 0x6a, 0x6a, 0xac, 0x5c, 0x8c, 0xae, 0x99, 0xdc, 0x20, 0xc5, 0x5e,
	0x87, 0xb3, 0xc8, 0x49, 0x82, 0x62, 0x62, 0xf1, 0x97, 0x03, 0xc1, 0x31, 0x4c, 0x42, 0x38, 0xb7,
	0xe0, 0xf8, 0xb2, 0x1f, 0x4a, 0x08, 0xb8, 0xdb, 0xa1, 0x33, 0x2b, 0xe6, 0xb6, 0xc5, 0xff, 0x75,
	0x92, 0x05, 0xc0, 0xba, 0xde, 0xef, 0x6b, 0xd6, 0xb7, 0x38, 0x84, 0xae, 0x2d, 0xfa, 0xa3, 0x90,
	0x5b, 0x08, 0xb6, 0x12, 0x69, 0xfb, 0x29, 0x55, 0x13, 0x7a, 0xd6, 0xfe, 0x15, 0xc8, 0x1d, 0x5c,
	0xae, 0xe4, 0xa1, 0x6b, 0x39, 0xf2, 0x9d, 0x4d, 0xf8, 0x36, 0x71, 0x2a, 0x2e, 0x9f, 0xdf, 0x9e,
	0xaa, 0x1a, 0xdf, 0xfb, 0x32, 0x63, 0xf2, 0x90, 0x2f, 0xa9, 0xa0, 0x82, 0xa6, 0x42, 0xa6, 0x54,
	0xd0, 0x5c, 0xf7, 0x5d, 0x27, 0x15, 0xa6, 0x58, 0xb3, 0x86, 0x63, 0x8a, 0x03, 0x93, 0x52, 0xe4,
	0x25, 0x65, 0x0d, 0x17, 0xbb, 0x7c, 0xfc, 0x9c, 0xd2, 0xb7, 0xe7, 0xe3, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x62, 0xa6, 0x20, 0x12, 0xad, 0x01, 0x00, 0x00,
}
