// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/case.proto

package protos // import "github.com/Banana-no-ana/support-ticket-tycoon/backend/protos"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CaseStatus int32

const (
	CaseStatus_New        CaseStatus = 0
	CaseStatus_Assigned   CaseStatus = 1
	CaseStatus_InProgress CaseStatus = 2
	CaseStatus_WOCR       CaseStatus = 3
	CaseStatus_Closed     CaseStatus = 4
)

var CaseStatus_name = map[int32]string{
	0: "New",
	1: "Assigned",
	2: "InProgress",
	3: "WOCR",
	4: "Closed",
}
var CaseStatus_value = map[string]int32{
	"New":        0,
	"Assigned":   1,
	"InProgress": 2,
	"WOCR":       3,
	"Closed":     4,
}

func (x CaseStatus) String() string {
	return proto.EnumName(CaseStatus_name, int32(x))
}
func (CaseStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_case_64eded3529fa66af, []int{0}
}

type StageStatus int32

const (
	StageStatus_Working   StageStatus = 0
	StageStatus_Completed StageStatus = 1
)

var StageStatus_name = map[int32]string{
	0: "Working",
	1: "Completed",
}
var StageStatus_value = map[string]int32{
	"Working":   0,
	"Completed": 1,
}

func (x StageStatus) String() string {
	return proto.EnumName(StageStatus_name, int32(x))
}
func (StageStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_case_64eded3529fa66af, []int{1}
}

type Case struct {
	CaseID               int32        `protobuf:"varint,1,opt,name=caseID,proto3" json:"caseID,omitempty"`
	Assignee             int32        `protobuf:"varint,2,opt,name=Assignee,proto3" json:"Assignee,omitempty"`
	CustomerID           int32        `protobuf:"varint,3,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	CurrentStage         int32        `protobuf:"varint,4,opt,name=CurrentStage,proto3" json:"CurrentStage,omitempty"`
	CustomerSentiment    int32        `protobuf:"varint,5,opt,name=CustomerSentiment,proto3" json:"CustomerSentiment,omitempty"`
	CaseStages           []*CaseStage `protobuf:"bytes,6,rep,name=CaseStages,proto3" json:"CaseStages,omitempty"`
	Status               CaseStatus   `protobuf:"varint,7,opt,name=Status,proto3,enum=case.CaseStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Case) Reset()         { *m = Case{} }
func (m *Case) String() string { return proto.CompactTextString(m) }
func (*Case) ProtoMessage()    {}
func (*Case) Descriptor() ([]byte, []int) {
	return fileDescriptor_case_64eded3529fa66af, []int{0}
}
func (m *Case) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Case.Unmarshal(m, b)
}
func (m *Case) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Case.Marshal(b, m, deterministic)
}
func (dst *Case) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Case.Merge(dst, src)
}
func (m *Case) XXX_Size() int {
	return xxx_messageInfo_Case.Size(m)
}
func (m *Case) XXX_DiscardUnknown() {
	xxx_messageInfo_Case.DiscardUnknown(m)
}

var xxx_messageInfo_Case proto.InternalMessageInfo

func (m *Case) GetCaseID() int32 {
	if m != nil {
		return m.CaseID
	}
	return 0
}

func (m *Case) GetAssignee() int32 {
	if m != nil {
		return m.Assignee
	}
	return 0
}

func (m *Case) GetCustomerID() int32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *Case) GetCurrentStage() int32 {
	if m != nil {
		return m.CurrentStage
	}
	return 0
}

func (m *Case) GetCustomerSentiment() int32 {
	if m != nil {
		return m.CustomerSentiment
	}
	return 0
}

func (m *Case) GetCaseStages() []*CaseStage {
	if m != nil {
		return m.CaseStages
	}
	return nil
}

func (m *Case) GetStatus() CaseStatus {
	if m != nil {
		return m.Status
	}
	return CaseStatus_New
}

type CaseStage struct {
	StageID              int32       `protobuf:"varint,1,opt,name=StageID,proto3" json:"StageID,omitempty"`
	Type                 SkillEnum   `protobuf:"varint,2,opt,name=Type,proto3,enum=utils.SkillEnum" json:"Type,omitempty"`
	Status               StageStatus `protobuf:"varint,3,opt,name=Status,proto3,enum=case.StageStatus" json:"Status,omitempty"`
	Difficulty           int32       `protobuf:"varint,4,opt,name=Difficulty,proto3" json:"Difficulty,omitempty"`
	Totalwork            int32       `protobuf:"varint,5,opt,name=Totalwork,proto3" json:"Totalwork,omitempty"`
	Completedwork        int32       `protobuf:"varint,6,opt,name=Completedwork,proto3" json:"Completedwork,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CaseStage) Reset()         { *m = CaseStage{} }
func (m *CaseStage) String() string { return proto.CompactTextString(m) }
func (*CaseStage) ProtoMessage()    {}
func (*CaseStage) Descriptor() ([]byte, []int) {
	return fileDescriptor_case_64eded3529fa66af, []int{1}
}
func (m *CaseStage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaseStage.Unmarshal(m, b)
}
func (m *CaseStage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaseStage.Marshal(b, m, deterministic)
}
func (dst *CaseStage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaseStage.Merge(dst, src)
}
func (m *CaseStage) XXX_Size() int {
	return xxx_messageInfo_CaseStage.Size(m)
}
func (m *CaseStage) XXX_DiscardUnknown() {
	xxx_messageInfo_CaseStage.DiscardUnknown(m)
}

var xxx_messageInfo_CaseStage proto.InternalMessageInfo

func (m *CaseStage) GetStageID() int32 {
	if m != nil {
		return m.StageID
	}
	return 0
}

func (m *CaseStage) GetType() SkillEnum {
	if m != nil {
		return m.Type
	}
	return SkillEnum_Troubleshoot
}

func (m *CaseStage) GetStatus() StageStatus {
	if m != nil {
		return m.Status
	}
	return StageStatus_Working
}

func (m *CaseStage) GetDifficulty() int32 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

func (m *CaseStage) GetTotalwork() int32 {
	if m != nil {
		return m.Totalwork
	}
	return 0
}

func (m *CaseStage) GetCompletedwork() int32 {
	if m != nil {
		return m.Completedwork
	}
	return 0
}

func init() {
	proto.RegisterType((*Case)(nil), "case.Case")
	proto.RegisterType((*CaseStage)(nil), "case.CaseStage")
	proto.RegisterEnum("case.CaseStatus", CaseStatus_name, CaseStatus_value)
	proto.RegisterEnum("case.StageStatus", StageStatus_name, StageStatus_value)
}

func init() { proto.RegisterFile("protos/case.proto", fileDescriptor_case_64eded3529fa66af) }

var fileDescriptor_case_64eded3529fa66af = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xc1, 0x6e, 0x9b, 0x40,
	0x10, 0x0d, 0x86, 0xe0, 0x78, 0x9c, 0xa4, 0x78, 0x0e, 0x15, 0x8a, 0xaa, 0xca, 0xb2, 0x72, 0x70,
	0xa2, 0xda, 0x48, 0xe9, 0xb9, 0xaa, 0x1a, 0xdc, 0x83, 0x2f, 0x6d, 0x85, 0x23, 0x45, 0xea, 0x6d,
	0x8d, 0x37, 0x14, 0x01, 0xbb, 0x68, 0x77, 0x56, 0x91, 0xbf, 0xa0, 0xff, 0xd8, 0xaf, 0xa9, 0x58,
	0x30, 0xb5, 0xd5, 0x13, 0x33, 0xef, 0xbd, 0x99, 0xc7, 0x3c, 0x80, 0x49, 0xad, 0x24, 0x49, 0x1d,
	0xa5, 0x4c, 0xf3, 0xa5, 0xad, 0xd1, 0x6b, 0xea, 0x1b, 0xec, 0x08, 0x43, 0x79, 0xa9, 0x5b, 0x66,
	0xf6, 0x7b, 0x00, 0x5e, 0xcc, 0x34, 0xc7, 0xb7, 0xe0, 0x37, 0xa2, 0xf5, 0x2a, 0x74, 0xa6, 0xce,
	0xfc, 0x3c, 0xe9, 0x3a, 0xbc, 0x81, 0x8b, 0x2f, 0x5a, 0xe7, 0x99, 0xe0, 0x3c, 0x1c, 0x58, 0xa6,
	0xef, 0xf1, 0x3d, 0x40, 0x6c, 0x34, 0xc9, 0x8a, 0xab, 0xf5, 0x2a, 0x74, 0x2d, 0x7b, 0x84, 0xe0,
	0x0c, 0x2e, 0x63, 0xa3, 0x14, 0x17, 0xb4, 0x21, 0x96, 0xf1, 0xd0, 0xb3, 0x8a, 0x13, 0x0c, 0x3f,
	0xc0, 0xe4, 0x30, 0xb1, 0xe1, 0x82, 0xf2, 0x8a, 0x0b, 0x0a, 0xcf, 0xad, 0xf0, 0x7f, 0x02, 0x23,
	0x80, 0xe6, 0x6d, 0xed, 0xa8, 0x0e, 0xfd, 0xa9, 0x3b, 0x1f, 0x3f, 0xbc, 0x59, 0xda, 0x4b, 0x7b,
	0x3c, 0x39, 0x92, 0xe0, 0x1c, 0xfc, 0x0d, 0x31, 0x32, 0x3a, 0x1c, 0x4e, 0x9d, 0xf9, 0xf5, 0x43,
	0x70, 0x22, 0x26, 0xa3, 0x93, 0x8e, 0x9f, 0xfd, 0x71, 0x60, 0xd4, 0x0f, 0x62, 0x08, 0x43, 0x5b,
	0xf4, 0x79, 0x1c, 0x5a, 0xbc, 0x05, 0xef, 0x69, 0x5f, 0xb7, 0x61, 0x34, 0xfb, 0xda, 0x34, 0x37,
	0x45, 0x5e, 0x96, 0x5f, 0x85, 0xa9, 0x12, 0xcb, 0xe2, 0x5d, 0xef, 0xeb, 0x5a, 0xdd, 0xa4, 0xf5,
	0xb5, 0x4b, 0x4e, 0x8d, 0x9b, 0x14, 0x57, 0xf9, 0xcb, 0x4b, 0x9e, 0x9a, 0x92, 0xf6, 0x5d, 0x46,
	0x47, 0x08, 0xbe, 0x83, 0xd1, 0x93, 0x24, 0x56, 0xbe, 0x4a, 0x55, 0x74, 0xc9, 0xfc, 0x03, 0xf0,
	0x16, 0xae, 0x62, 0x59, 0xd5, 0x25, 0x27, 0xbe, 0xb3, 0x0a, 0xdf, 0x2a, 0x4e, 0xc1, 0xfb, 0x75,
	0x9f, 0x5b, 0xe3, 0x38, 0x04, 0xf7, 0x1b, 0x7f, 0x0d, 0xce, 0xf0, 0xb2, 0xff, 0xb8, 0xbb, 0xc0,
	0xc1, 0x6b, 0x80, 0xb5, 0xf8, 0xa1, 0x64, 0xa6, 0xb8, 0xd6, 0xc1, 0x00, 0x2f, 0xc0, 0x7b, 0xfe,
	0x1e, 0x27, 0x81, 0x8b, 0x00, 0x7e, 0x5c, 0x4a, 0xcd, 0x77, 0x81, 0x77, 0x7f, 0x07, 0xe3, 0xa3,
	0x2b, 0x70, 0x0c, 0xc3, 0x67, 0xa9, 0x8a, 0x5c, 0x64, 0xc1, 0x19, 0x5e, 0xc1, 0xa8, 0xf7, 0x0d,
	0x9c, 0xc7, 0xcf, 0x3f, 0x3f, 0x65, 0x39, 0xfd, 0x32, 0xdb, 0x65, 0x2a, 0xab, 0xe8, 0x91, 0x09,
	0x26, 0xd8, 0x42, 0xc8, 0x05, 0x13, 0x2c, 0xd2, 0xa6, 0xae, 0xa5, 0xa2, 0x05, 0xe5, 0x69, 0xc1,
	0x69, 0x41, 0xfb, 0x54, 0x4a, 0x11, 0x6d, 0x59, 0x5a, 0x70, 0xb1, 0x8b, 0xda, 0x3f, 0x75, 0xeb,
	0xdb, 0xe7, 0xc7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x54, 0xe4, 0x6d, 0xd3, 0x02, 0x00,
	0x00,
}
