//Define working with cases.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.0
// source: protos/clock.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *WorkerRegister) Reset() {
	*x = WorkerRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_clock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRegister) ProtoMessage() {}

func (x *WorkerRegister) ProtoReflect() protoreflect.Message {
	mi := &file_protos_clock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRegister.ProtoReflect.Descriptor instead.
func (*WorkerRegister) Descriptor() ([]byte, []int) {
	return file_protos_clock_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerRegister) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Tick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TickNum int32 `protobuf:"varint,1,opt,name=TickNum,proto3" json:"TickNum,omitempty"`
}

func (x *Tick) Reset() {
	*x = Tick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_clock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tick) ProtoMessage() {}

func (x *Tick) ProtoReflect() protoreflect.Message {
	mi := &file_protos_clock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tick.ProtoReflect.Descriptor instead.
func (*Tick) Descriptor() ([]byte, []int) {
	return file_protos_clock_proto_rawDescGZIP(), []int{1}
}

func (x *Tick) GetTickNum() int32 {
	if x != nil {
		return x.TickNum
	}
	return 0
}

var File_protos_clock_proto protoreflect.FileDescriptor

var file_protos_clock_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x20, 0x0a, 0x0e, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x20, 0x0a,
	0x04, 0x54, 0x69, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x69, 0x63, 0x6b, 0x4e, 0x75, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x54, 0x69, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x32,
	0x39, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x30, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x57, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x1a, 0x0b, 0x2e, 0x63, 0x6c,
	0x6f, 0x63, 0x6b, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x30, 0x01, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x61, 0x6e, 0x61, 0x6e, 0x61, 0x2d,
	0x6e, 0x6f, 0x2d, 0x61, 0x6e, 0x61, 0x2f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2d, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x2d, 0x74, 0x79, 0x63, 0x6f, 0x6f, 0x6e, 0x2f, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_clock_proto_rawDescOnce sync.Once
	file_protos_clock_proto_rawDescData = file_protos_clock_proto_rawDesc
)

func file_protos_clock_proto_rawDescGZIP() []byte {
	file_protos_clock_proto_rawDescOnce.Do(func() {
		file_protos_clock_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_clock_proto_rawDescData)
	})
	return file_protos_clock_proto_rawDescData
}

var file_protos_clock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_clock_proto_goTypes = []interface{}{
	(*WorkerRegister)(nil), // 0: clock.WorkerRegister
	(*Tick)(nil),           // 1: clock.Tick
}
var file_protos_clock_proto_depIdxs = []int32{
	0, // 0: clock.Clock.Register:input_type -> clock.WorkerRegister
	1, // 1: clock.Clock.Register:output_type -> clock.Tick
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_clock_proto_init() }
func file_protos_clock_proto_init() {
	if File_protos_clock_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_clock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_clock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_clock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_clock_proto_goTypes,
		DependencyIndexes: file_protos_clock_proto_depIdxs,
		MessageInfos:      file_protos_clock_proto_msgTypes,
	}.Build()
	File_protos_clock_proto = out.File
	file_protos_clock_proto_rawDesc = nil
	file_protos_clock_proto_goTypes = nil
	file_protos_clock_proto_depIdxs = nil
}
