// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CustomerClient is the client API for Customer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomerClient interface {
	//API registers a case with the customer service.
	RegisterCase(ctx context.Context, in *Case, opts ...grpc.CallOption) (*Response, error)
	//Ask the customer if the case has expired
	GetCaseStatus(ctx context.Context, in *Case, opts ...grpc.CallOption) (*Case, error)
	//Set the scenario difficulty
	SetDifficulty(ctx context.Context, in *Difficulty, opts ...grpc.CallOption) (*Response, error)
	//Worker lets the customer know the stage is done, and customer gives the next stage.
	//Worker gives the completed current stage, and customer calculates if there's a next stage.
	//If there is, then that is returned, if not, then customer returns case is complete.
	CustomerReply(ctx context.Context, in *Case, opts ...grpc.CallOption) (*Case, error)
}

type customerClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerClient(cc grpc.ClientConnInterface) CustomerClient {
	return &customerClient{cc}
}

func (c *customerClient) RegisterCase(ctx context.Context, in *Case, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/customer.Customer/RegisterCase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) GetCaseStatus(ctx context.Context, in *Case, opts ...grpc.CallOption) (*Case, error) {
	out := new(Case)
	err := c.cc.Invoke(ctx, "/customer.Customer/GetCaseStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) SetDifficulty(ctx context.Context, in *Difficulty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/customer.Customer/SetDifficulty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) CustomerReply(ctx context.Context, in *Case, opts ...grpc.CallOption) (*Case, error) {
	out := new(Case)
	err := c.cc.Invoke(ctx, "/customer.Customer/CustomerReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServer is the server API for Customer service.
// All implementations must embed UnimplementedCustomerServer
// for forward compatibility
type CustomerServer interface {
	//API registers a case with the customer service.
	RegisterCase(context.Context, *Case) (*Response, error)
	//Ask the customer if the case has expired
	GetCaseStatus(context.Context, *Case) (*Case, error)
	//Set the scenario difficulty
	SetDifficulty(context.Context, *Difficulty) (*Response, error)
	//Worker lets the customer know the stage is done, and customer gives the next stage.
	//Worker gives the completed current stage, and customer calculates if there's a next stage.
	//If there is, then that is returned, if not, then customer returns case is complete.
	CustomerReply(context.Context, *Case) (*Case, error)
	mustEmbedUnimplementedCustomerServer()
}

// UnimplementedCustomerServer must be embedded to have forward compatible implementations.
type UnimplementedCustomerServer struct {
}

func (UnimplementedCustomerServer) RegisterCase(context.Context, *Case) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCase not implemented")
}
func (UnimplementedCustomerServer) GetCaseStatus(context.Context, *Case) (*Case, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCaseStatus not implemented")
}
func (UnimplementedCustomerServer) SetDifficulty(context.Context, *Difficulty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDifficulty not implemented")
}
func (UnimplementedCustomerServer) CustomerReply(context.Context, *Case) (*Case, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomerReply not implemented")
}
func (UnimplementedCustomerServer) mustEmbedUnimplementedCustomerServer() {}

// UnsafeCustomerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerServer will
// result in compilation errors.
type UnsafeCustomerServer interface {
	mustEmbedUnimplementedCustomerServer()
}

func RegisterCustomerServer(s grpc.ServiceRegistrar, srv CustomerServer) {
	s.RegisterService(&Customer_ServiceDesc, srv)
}

func _Customer_RegisterCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Case)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).RegisterCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.Customer/RegisterCase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).RegisterCase(ctx, req.(*Case))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_GetCaseStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Case)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).GetCaseStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.Customer/GetCaseStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).GetCaseStatus(ctx, req.(*Case))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_SetDifficulty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Difficulty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).SetDifficulty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.Customer/SetDifficulty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).SetDifficulty(ctx, req.(*Difficulty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_CustomerReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Case)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).CustomerReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.Customer/CustomerReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).CustomerReply(ctx, req.(*Case))
	}
	return interceptor(ctx, in, info, handler)
}

// Customer_ServiceDesc is the grpc.ServiceDesc for Customer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Customer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customer.Customer",
	HandlerType: (*CustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCase",
			Handler:    _Customer_RegisterCase_Handler,
		},
		{
			MethodName: "GetCaseStatus",
			Handler:    _Customer_GetCaseStatus_Handler,
		},
		{
			MethodName: "SetDifficulty",
			Handler:    _Customer_SetDifficulty_Handler,
		},
		{
			MethodName: "CustomerReply",
			Handler:    _Customer_CustomerReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/customer.proto",
}
