// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/utils.proto

package protos // import "github.com/Banana-no-ana/support-ticket-tycoon/backend/protos"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_utils_c868161edaf4c0fd, []int{0}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Set scenario difficulty
type Difficulty struct {
	MinDifficulty        int32    `protobuf:"varint,1,opt,name=minDifficulty,proto3" json:"minDifficulty,omitempty"`
	MaxDifficulty        int32    `protobuf:"varint,2,opt,name=maxDifficulty,proto3" json:"maxDifficulty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Difficulty) Reset()         { *m = Difficulty{} }
func (m *Difficulty) String() string { return proto.CompactTextString(m) }
func (*Difficulty) ProtoMessage()    {}
func (*Difficulty) Descriptor() ([]byte, []int) {
	return fileDescriptor_utils_c868161edaf4c0fd, []int{1}
}
func (m *Difficulty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Difficulty.Unmarshal(m, b)
}
func (m *Difficulty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Difficulty.Marshal(b, m, deterministic)
}
func (dst *Difficulty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Difficulty.Merge(dst, src)
}
func (m *Difficulty) XXX_Size() int {
	return xxx_messageInfo_Difficulty.Size(m)
}
func (m *Difficulty) XXX_DiscardUnknown() {
	xxx_messageInfo_Difficulty.DiscardUnknown(m)
}

var xxx_messageInfo_Difficulty proto.InternalMessageInfo

func (m *Difficulty) GetMinDifficulty() int32 {
	if m != nil {
		return m.MinDifficulty
	}
	return 0
}

func (m *Difficulty) GetMaxDifficulty() int32 {
	if m != nil {
		return m.MaxDifficulty
	}
	return 0
}

func init() {
	proto.RegisterType((*Response)(nil), "utils.Response")
	proto.RegisterType((*Difficulty)(nil), "utils.Difficulty")
}

func init() { proto.RegisterFile("protos/utils.proto", fileDescriptor_utils_c868161edaf4c0fd) }

var fileDescriptor_utils_c868161edaf4c0fd = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xb1, 0xca, 0xc2, 0x30,
	0x14, 0x46, 0xe9, 0x0f, 0xfd, 0x2d, 0x01, 0x97, 0x4c, 0x1d, 0xa5, 0x74, 0x70, 0x49, 0x33, 0x38,
	0x8b, 0x50, 0x7c, 0x82, 0xba, 0x88, 0x5b, 0x1a, 0x53, 0x0d, 0x6d, 0xef, 0x0d, 0xcd, 0x0d, 0xd8,
	0xb7, 0x17, 0xa2, 0x62, 0x9d, 0x3e, 0xce, 0xe1, 0x2c, 0x1f, 0xe3, 0x6e, 0x42, 0x42, 0x2f, 0x03,
	0xd9, 0xc1, 0x57, 0x11, 0x78, 0x1a, 0xa1, 0x28, 0x59, 0xd6, 0x18, 0xef, 0x10, 0xbc, 0xe1, 0x39,
	0x5b, 0x9d, 0x82, 0xd6, 0xc6, 0xfb, 0x3c, 0xd9, 0x24, 0xdb, 0xac, 0xf9, 0x60, 0x71, 0x66, 0xec,
	0x68, 0xbb, 0xce, 0xea, 0x30, 0xd0, 0xcc, 0x4b, 0xb6, 0x1e, 0x2d, 0x7c, 0x45, 0xac, 0xd3, 0xe6,
	0x57, 0xc6, 0x4a, 0x3d, 0x16, 0xd5, 0xdf, 0xbb, 0x5a, 0xca, 0xfa, 0x70, 0xd9, 0xdf, 0x2c, 0xdd,
	0x43, 0x5b, 0x69, 0x1c, 0x65, 0xad, 0x40, 0x81, 0x12, 0x80, 0x42, 0x81, 0x92, 0x3e, 0x38, 0x87,
	0x13, 0x09, 0xb2, 0xba, 0x37, 0x24, 0x68, 0xd6, 0x88, 0x20, 0x5b, 0xa5, 0x7b, 0x03, 0x57, 0xf9,
	0xfa, 0xd4, 0xfe, 0xc7, 0xdd, 0x3d, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x38, 0xf3, 0x3a, 0xe4,
	0x00, 0x00, 0x00,
}
