// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.0
// source: protos/utils.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SkillEnum int32

const (
	SkillEnum_Troubleshoot SkillEnum = 0
	SkillEnum_Build        SkillEnum = 1
	SkillEnum_Tech         SkillEnum = 2
	SkillEnum_Usage        SkillEnum = 3
	SkillEnum_Architecture SkillEnum = 4
	SkillEnum_Environment  SkillEnum = 5
	SkillEnum_Explain      SkillEnum = 6
	SkillEnum_Empathy      SkillEnum = 7
	SkillEnum_Relationship SkillEnum = 8 //Relationship Management
)

// Enum value maps for SkillEnum.
var (
	SkillEnum_name = map[int32]string{
		0: "Troubleshoot",
		1: "Build",
		2: "Tech",
		3: "Usage",
		4: "Architecture",
		5: "Environment",
		6: "Explain",
		7: "Empathy",
		8: "Relationship",
	}
	SkillEnum_value = map[string]int32{
		"Troubleshoot": 0,
		"Build":        1,
		"Tech":         2,
		"Usage":        3,
		"Architecture": 4,
		"Environment":  5,
		"Explain":      6,
		"Empathy":      7,
		"Relationship": 8,
	}
)

func (x SkillEnum) Enum() *SkillEnum {
	p := new(SkillEnum)
	*p = x
	return p
}

func (x SkillEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SkillEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_utils_proto_enumTypes[0].Descriptor()
}

func (SkillEnum) Type() protoreflect.EnumType {
	return &file_protos_utils_proto_enumTypes[0]
}

func (x SkillEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SkillEnum.Descriptor instead.
func (SkillEnum) EnumDescriptor() ([]byte, []int) {
	return file_protos_utils_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_utils_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_utils_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protos_utils_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

//Set scenario difficulty
type Difficulty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinDifficulty int32 `protobuf:"varint,1,opt,name=minDifficulty,proto3" json:"minDifficulty,omitempty"`
	MaxDifficulty int32 `protobuf:"varint,2,opt,name=maxDifficulty,proto3" json:"maxDifficulty,omitempty"`
}

func (x *Difficulty) Reset() {
	*x = Difficulty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_utils_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Difficulty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Difficulty) ProtoMessage() {}

func (x *Difficulty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_utils_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Difficulty.ProtoReflect.Descriptor instead.
func (*Difficulty) Descriptor() ([]byte, []int) {
	return file_protos_utils_proto_rawDescGZIP(), []int{1}
}

func (x *Difficulty) GetMinDifficulty() int32 {
	if x != nil {
		return x.MinDifficulty
	}
	return 0
}

func (x *Difficulty) GetMaxDifficulty() int32 {
	if x != nil {
		return x.MaxDifficulty
	}
	return 0
}

var File_protos_utils_proto protoreflect.FileDescriptor

var file_protos_utils_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x22, 0x24, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x58, 0x0a, 0x0a, 0x44, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12,
	0x24, 0x0a, 0x0d, 0x6d, 0x69, 0x6e, 0x44, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6d, 0x69, 0x6e, 0x44, 0x69, 0x66, 0x66, 0x69,
	0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x44, 0x69, 0x66, 0x66,
	0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6d, 0x61,
	0x78, 0x44, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x2a, 0x8c, 0x01, 0x0a, 0x09,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x72, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x65, 0x63, 0x68, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x55, 0x73, 0x61, 0x67, 0x65, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x10, 0x04, 0x12, 0x0f, 0x0a,
	0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x10, 0x05, 0x12, 0x0b,
	0x0a, 0x07, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x45,
	0x6d, 0x70, 0x61, 0x74, 0x68, 0x79, 0x10, 0x07, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x10, 0x08, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x61, 0x6e, 0x61, 0x6e, 0x61, 0x2d,
	0x6e, 0x6f, 0x2d, 0x61, 0x6e, 0x61, 0x2f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2d, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x2d, 0x74, 0x79, 0x63, 0x6f, 0x6f, 0x6e, 0x2f, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_utils_proto_rawDescOnce sync.Once
	file_protos_utils_proto_rawDescData = file_protos_utils_proto_rawDesc
)

func file_protos_utils_proto_rawDescGZIP() []byte {
	file_protos_utils_proto_rawDescOnce.Do(func() {
		file_protos_utils_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_utils_proto_rawDescData)
	})
	return file_protos_utils_proto_rawDescData
}

var file_protos_utils_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_utils_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_utils_proto_goTypes = []interface{}{
	(SkillEnum)(0),     // 0: utils.SkillEnum
	(*Response)(nil),   // 1: utils.Response
	(*Difficulty)(nil), // 2: utils.Difficulty
}
var file_protos_utils_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_utils_proto_init() }
func file_protos_utils_proto_init() {
	if File_protos_utils_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_utils_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_utils_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Difficulty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_utils_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_utils_proto_goTypes,
		DependencyIndexes: file_protos_utils_proto_depIdxs,
		EnumInfos:         file_protos_utils_proto_enumTypes,
		MessageInfos:      file_protos_utils_proto_msgTypes,
	}.Build()
	File_protos_utils_proto = out.File
	file_protos_utils_proto_rawDesc = nil
	file_protos_utils_proto_goTypes = nil
	file_protos_utils_proto_depIdxs = nil
}
