// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/worker.proto

package protos // import "github.com/Banana-no-ana/support-ticket-tycoon/backend/protos"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Case struct {
	CaseID               int32    `protobuf:"varint,1,opt,name=caseID,proto3" json:"caseID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Case) Reset()         { *m = Case{} }
func (m *Case) String() string { return proto.CompactTextString(m) }
func (*Case) ProtoMessage()    {}
func (*Case) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_ea09b05b3fedf6d2, []int{0}
}
func (m *Case) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Case.Unmarshal(m, b)
}
func (m *Case) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Case.Marshal(b, m, deterministic)
}
func (dst *Case) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Case.Merge(dst, src)
}
func (m *Case) XXX_Size() int {
	return xxx_messageInfo_Case.Size(m)
}
func (m *Case) XXX_DiscardUnknown() {
	xxx_messageInfo_Case.DiscardUnknown(m)
}

var xxx_messageInfo_Case proto.InternalMessageInfo

func (m *Case) GetCaseID() int32 {
	if m != nil {
		return m.CaseID
	}
	return 0
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_ea09b05b3fedf6d2, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CaseState struct {
	CurrentStage         int32        `protobuf:"varint,1,opt,name=currentStage,proto3" json:"currentStage,omitempty"`
	Stage                []*CaseStage `protobuf:"bytes,2,rep,name=Stage,proto3" json:"Stage,omitempty"`
	Status               string       `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CaseState) Reset()         { *m = CaseState{} }
func (m *CaseState) String() string { return proto.CompactTextString(m) }
func (*CaseState) ProtoMessage()    {}
func (*CaseState) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_ea09b05b3fedf6d2, []int{2}
}
func (m *CaseState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaseState.Unmarshal(m, b)
}
func (m *CaseState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaseState.Marshal(b, m, deterministic)
}
func (dst *CaseState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaseState.Merge(dst, src)
}
func (m *CaseState) XXX_Size() int {
	return xxx_messageInfo_CaseState.Size(m)
}
func (m *CaseState) XXX_DiscardUnknown() {
	xxx_messageInfo_CaseState.DiscardUnknown(m)
}

var xxx_messageInfo_CaseState proto.InternalMessageInfo

func (m *CaseState) GetCurrentStage() int32 {
	if m != nil {
		return m.CurrentStage
	}
	return 0
}

func (m *CaseState) GetStage() []*CaseStage {
	if m != nil {
		return m.Stage
	}
	return nil
}

func (m *CaseState) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type CaseStage struct {
	StageID              int32    `protobuf:"varint,1,opt,name=StageID,proto3" json:"StageID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Difficulty           int32    `protobuf:"varint,4,opt,name=Difficulty,proto3" json:"Difficulty,omitempty"`
	Totalwork            int32    `protobuf:"varint,5,opt,name=Totalwork,proto3" json:"Totalwork,omitempty"`
	Completedwork        int32    `protobuf:"varint,6,opt,name=Completedwork,proto3" json:"Completedwork,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaseStage) Reset()         { *m = CaseStage{} }
func (m *CaseStage) String() string { return proto.CompactTextString(m) }
func (*CaseStage) ProtoMessage()    {}
func (*CaseStage) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_ea09b05b3fedf6d2, []int{3}
}
func (m *CaseStage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaseStage.Unmarshal(m, b)
}
func (m *CaseStage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaseStage.Marshal(b, m, deterministic)
}
func (dst *CaseStage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaseStage.Merge(dst, src)
}
func (m *CaseStage) XXX_Size() int {
	return xxx_messageInfo_CaseStage.Size(m)
}
func (m *CaseStage) XXX_DiscardUnknown() {
	xxx_messageInfo_CaseStage.DiscardUnknown(m)
}

var xxx_messageInfo_CaseStage proto.InternalMessageInfo

func (m *CaseStage) GetStageID() int32 {
	if m != nil {
		return m.StageID
	}
	return 0
}

func (m *CaseStage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CaseStage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CaseStage) GetDifficulty() int32 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

func (m *CaseStage) GetTotalwork() int32 {
	if m != nil {
		return m.Totalwork
	}
	return 0
}

func (m *CaseStage) GetCompletedwork() int32 {
	if m != nil {
		return m.Completedwork
	}
	return 0
}

type WorkerSkill struct {
	Troubleshoot         int32    `protobuf:"varint,1,opt,name=Troubleshoot,proto3" json:"Troubleshoot,omitempty"`
	Build                int32    `protobuf:"varint,2,opt,name=Build,proto3" json:"Build,omitempty"`
	Tech                 int32    `protobuf:"varint,3,opt,name=Tech,proto3" json:"Tech,omitempty"`
	Usage                int32    `protobuf:"varint,4,opt,name=Usage,proto3" json:"Usage,omitempty"`
	Architecture         int32    `protobuf:"varint,5,opt,name=Architecture,proto3" json:"Architecture,omitempty"`
	Environment          int32    `protobuf:"varint,6,opt,name=Environment,proto3" json:"Environment,omitempty"`
	Explain              int32    `protobuf:"varint,7,opt,name=Explain,proto3" json:"Explain,omitempty"`
	Empathy              int32    `protobuf:"varint,8,opt,name=Empathy,proto3" json:"Empathy,omitempty"`
	Relationship         int32    `protobuf:"varint,9,opt,name=Relationship,proto3" json:"Relationship,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerSkill) Reset()         { *m = WorkerSkill{} }
func (m *WorkerSkill) String() string { return proto.CompactTextString(m) }
func (*WorkerSkill) ProtoMessage()    {}
func (*WorkerSkill) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_ea09b05b3fedf6d2, []int{4}
}
func (m *WorkerSkill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerSkill.Unmarshal(m, b)
}
func (m *WorkerSkill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerSkill.Marshal(b, m, deterministic)
}
func (dst *WorkerSkill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerSkill.Merge(dst, src)
}
func (m *WorkerSkill) XXX_Size() int {
	return xxx_messageInfo_WorkerSkill.Size(m)
}
func (m *WorkerSkill) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerSkill.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerSkill proto.InternalMessageInfo

func (m *WorkerSkill) GetTroubleshoot() int32 {
	if m != nil {
		return m.Troubleshoot
	}
	return 0
}

func (m *WorkerSkill) GetBuild() int32 {
	if m != nil {
		return m.Build
	}
	return 0
}

func (m *WorkerSkill) GetTech() int32 {
	if m != nil {
		return m.Tech
	}
	return 0
}

func (m *WorkerSkill) GetUsage() int32 {
	if m != nil {
		return m.Usage
	}
	return 0
}

func (m *WorkerSkill) GetArchitecture() int32 {
	if m != nil {
		return m.Architecture
	}
	return 0
}

func (m *WorkerSkill) GetEnvironment() int32 {
	if m != nil {
		return m.Environment
	}
	return 0
}

func (m *WorkerSkill) GetExplain() int32 {
	if m != nil {
		return m.Explain
	}
	return 0
}

func (m *WorkerSkill) GetEmpathy() int32 {
	if m != nil {
		return m.Empathy
	}
	return 0
}

func (m *WorkerSkill) GetRelationship() int32 {
	if m != nil {
		return m.Relationship
	}
	return 0
}

func init() {
	proto.RegisterType((*Case)(nil), "worker.Case")
	proto.RegisterType((*Response)(nil), "worker.Response")
	proto.RegisterType((*CaseState)(nil), "worker.CaseState")
	proto.RegisterType((*CaseStage)(nil), "worker.CaseStage")
	proto.RegisterType((*WorkerSkill)(nil), "worker.WorkerSkill")
}

func init() { proto.RegisterFile("protos/worker.proto", fileDescriptor_worker_ea09b05b3fedf6d2) }

var fileDescriptor_worker_ea09b05b3fedf6d2 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0xb6, 0x26, 0x6b, 0x6f, 0x8b, 0x00, 0x0f, 0xa1, 0x08, 0xa1, 0xa9, 0x8a, 0x26, 0x51,
	0x81, 0xda, 0xc2, 0x78, 0xe1, 0x05, 0xa1, 0x75, 0x9b, 0x80, 0xd7, 0xb4, 0x13, 0x12, 0x6f, 0xae,
	0x7b, 0xd7, 0x58, 0x4d, 0xed, 0x28, 0xbe, 0x01, 0xfa, 0x15, 0x7c, 0x0d, 0xff, 0xc6, 0x23, 0xb2,
	0x9d, 0x76, 0x29, 0x0c, 0x69, 0x4f, 0xf1, 0x39, 0xf7, 0xe4, 0xde, 0x73, 0x8f, 0x6c, 0x38, 0x2e,
	0x4a, 0x4d, 0xda, 0x8c, 0xbf, 0xeb, 0x72, 0x85, 0xe5, 0xc8, 0x21, 0x16, 0x79, 0x94, 0x9c, 0x40,
	0xeb, 0x82, 0x1b, 0x64, 0x4f, 0x21, 0x12, 0xdc, 0xe0, 0xe7, 0xcb, 0x38, 0xe8, 0x07, 0x83, 0x30,
	0xad, 0x51, 0x72, 0x0a, 0xed, 0x14, 0x4d, 0xa1, 0x95, 0x41, 0x16, 0xc3, 0xd1, 0xb4, 0x12, 0x02,
	0x8d, 0x71, 0xa2, 0x76, 0xba, 0x85, 0x49, 0x01, 0x1d, 0xdb, 0x65, 0x4a, 0x9c, 0x90, 0x25, 0xd0,
	0x13, 0x55, 0x59, 0xa2, 0xa2, 0x29, 0xf1, 0x25, 0xd6, 0x0d, 0xf7, 0x38, 0xf6, 0x02, 0x42, 0x5f,
	0x3c, 0xe8, 0x1f, 0x0e, 0xba, 0x67, 0x8f, 0x47, 0xb5, 0xb9, 0xba, 0xcb, 0x12, 0x53, 0x5f, 0xb7,
	0xbe, 0x6c, 0xd7, 0xca, 0xc4, 0x87, 0xfd, 0x60, 0xd0, 0x49, 0x6b, 0x94, 0xfc, 0x0a, 0x76, 0x23,
	0x97, 0xde, 0x99, 0x3d, 0xec, 0xec, 0x6f, 0x21, 0x63, 0xd0, 0x9a, 0x6d, 0x0a, 0x3b, 0xc7, 0xfe,
	0xed, 0xce, 0xff, 0xeb, 0xc9, 0x4e, 0x00, 0x2e, 0xe5, 0xcd, 0x8d, 0x14, 0x55, 0x4e, 0x9b, 0xb8,
	0xe5, 0x1a, 0x35, 0x18, 0xf6, 0x1c, 0x3a, 0x33, 0x4d, 0x3c, 0xb7, 0x5e, 0xe3, 0xd0, 0x95, 0x6f,
	0x09, 0x76, 0x0a, 0x0f, 0x2e, 0xf4, 0xba, 0xc8, 0x91, 0x70, 0xe1, 0x14, 0x91, 0x53, 0xec, 0x93,
	0xc9, 0xcf, 0x03, 0xe8, 0x7e, 0x71, 0xbb, 0x4e, 0x57, 0x32, 0xcf, 0x6d, 0x58, 0xb3, 0x52, 0x57,
	0xf3, 0x1c, 0x4d, 0xa6, 0x35, 0x6d, 0xc3, 0x6a, 0x72, 0xec, 0x09, 0x84, 0x93, 0x4a, 0xe6, 0x0b,
	0xb7, 0x44, 0x98, 0x7a, 0xe0, 0x36, 0x43, 0x91, 0xb9, 0x1d, 0xc2, 0xd4, 0x9d, 0xad, 0xf2, 0xda,
	0xd8, 0x58, 0xbd, 0x79, 0x0f, 0xec, 0x8c, 0xf3, 0x52, 0x64, 0x92, 0x50, 0x50, 0x55, 0x62, 0x6d,
	0x7d, 0x8f, 0x63, 0x7d, 0xe8, 0x5e, 0xa9, 0x6f, 0xb2, 0xd4, 0x6a, 0x8d, 0x8a, 0x6a, 0xef, 0x4d,
	0xca, 0x66, 0x7c, 0xf5, 0xa3, 0xc8, 0xb9, 0x54, 0xf1, 0x91, 0xcf, 0xb8, 0x86, 0xae, 0xb2, 0x2e,
	0x38, 0x65, 0x9b, 0xb8, 0x5d, 0x57, 0x3c, 0xb4, 0x93, 0x53, 0xcc, 0x39, 0x49, 0xad, 0x4c, 0x26,
	0x8b, 0xb8, 0xe3, 0x27, 0x37, 0xb9, 0xb3, 0xdf, 0x01, 0x44, 0x3e, 0x11, 0x36, 0x80, 0xe8, 0xdc,
	0x18, 0xb9, 0x54, 0xac, 0xd7, 0xbc, 0x10, 0xcf, 0x1e, 0x6d, 0xd1, 0xee, 0x2a, 0xbe, 0x84, 0xf6,
	0xb5, 0xe2, 0xf7, 0xd3, 0xbe, 0x83, 0x87, 0x53, 0xa4, 0x46, 0xe8, 0x86, 0x1d, 0x6f, 0x45, 0x0d,
	0xf6, 0x8e, 0x3f, 0x5f, 0x41, 0xf8, 0x09, 0xf3, 0x5c, 0xb3, 0x7f, 0x4a, 0x77, 0x88, 0xdf, 0x40,
	0xef, 0x23, 0xd2, 0xed, 0x33, 0xd8, 0xb7, 0xf5, 0xf7, 0x0d, 0x27, 0x7c, 0x1d, 0x4c, 0x3e, 0x7c,
	0x7d, 0xbf, 0x94, 0x94, 0x55, 0xf3, 0x91, 0xd0, 0xeb, 0xf1, 0x84, 0x2b, 0xae, 0xf8, 0x50, 0xe9,
	0x21, 0x57, 0x7c, 0x6c, 0xaa, 0xa2, 0xd0, 0x25, 0x0d, 0x49, 0x8a, 0x15, 0xd2, 0x90, 0x36, 0x42,
	0x6b, 0x35, 0x9e, 0x73, 0xb1, 0x42, 0xb5, 0x18, 0xfb, 0x27, 0x3d, 0x8f, 0xdc, 0xf7, 0xed, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x31, 0xa8, 0xcb, 0xe3, 0x03, 0x00, 0x00,
}
