// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/worker.proto

package protos // import "github.com/Banana-no-ana/support-ticket-tycoon/backend/protos"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Case struct {
	CaseID               int32    `protobuf:"varint,1,opt,name=caseID,proto3" json:"caseID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Case) Reset()         { *m = Case{} }
func (m *Case) String() string { return proto.CompactTextString(m) }
func (*Case) ProtoMessage()    {}
func (*Case) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_d4b816c21ba5759b, []int{0}
}
func (m *Case) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Case.Unmarshal(m, b)
}
func (m *Case) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Case.Marshal(b, m, deterministic)
}
func (dst *Case) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Case.Merge(dst, src)
}
func (m *Case) XXX_Size() int {
	return xxx_messageInfo_Case.Size(m)
}
func (m *Case) XXX_DiscardUnknown() {
	xxx_messageInfo_Case.DiscardUnknown(m)
}

var xxx_messageInfo_Case proto.InternalMessageInfo

func (m *Case) GetCaseID() int32 {
	if m != nil {
		return m.CaseID
	}
	return 0
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_d4b816c21ba5759b, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Update message to the case repo
type CaseUpdate struct {
	CaseID               int32    `protobuf:"varint,1,opt,name=CaseID,proto3" json:"CaseID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaseUpdate) Reset()         { *m = CaseUpdate{} }
func (m *CaseUpdate) String() string { return proto.CompactTextString(m) }
func (*CaseUpdate) ProtoMessage()    {}
func (*CaseUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_d4b816c21ba5759b, []int{2}
}
func (m *CaseUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaseUpdate.Unmarshal(m, b)
}
func (m *CaseUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaseUpdate.Marshal(b, m, deterministic)
}
func (dst *CaseUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaseUpdate.Merge(dst, src)
}
func (m *CaseUpdate) XXX_Size() int {
	return xxx_messageInfo_CaseUpdate.Size(m)
}
func (m *CaseUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_CaseUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_CaseUpdate proto.InternalMessageInfo

func (m *CaseUpdate) GetCaseID() int32 {
	if m != nil {
		return m.CaseID
	}
	return 0
}

type CaseDetail struct {
	CaseID               int32    `protobuf:"varint,1,opt,name=CaseID,proto3" json:"CaseID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaseDetail) Reset()         { *m = CaseDetail{} }
func (m *CaseDetail) String() string { return proto.CompactTextString(m) }
func (*CaseDetail) ProtoMessage()    {}
func (*CaseDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_d4b816c21ba5759b, []int{3}
}
func (m *CaseDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaseDetail.Unmarshal(m, b)
}
func (m *CaseDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaseDetail.Marshal(b, m, deterministic)
}
func (dst *CaseDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaseDetail.Merge(dst, src)
}
func (m *CaseDetail) XXX_Size() int {
	return xxx_messageInfo_CaseDetail.Size(m)
}
func (m *CaseDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_CaseDetail.DiscardUnknown(m)
}

var xxx_messageInfo_CaseDetail proto.InternalMessageInfo

func (m *CaseDetail) GetCaseID() int32 {
	if m != nil {
		return m.CaseID
	}
	return 0
}

func init() {
	proto.RegisterType((*Case)(nil), "worker.Case")
	proto.RegisterType((*Response)(nil), "worker.Response")
	proto.RegisterType((*CaseUpdate)(nil), "worker.CaseUpdate")
	proto.RegisterType((*CaseDetail)(nil), "worker.CaseDetail")
}

func init() { proto.RegisterFile("protos/worker.proto", fileDescriptor_worker_d4b816c21ba5759b) }

var fileDescriptor_worker_d4b816c21ba5759b = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x46, 0x29, 0xe8, 0x1a, 0x06, 0x0f, 0xb2, 0x82, 0x14, 0x0f, 0x22, 0xa1, 0x87, 0x22, 0x24,
	0x0b, 0x7a, 0x16, 0xb1, 0xe9, 0xc5, 0x6b, 0xa4, 0x08, 0x1e, 0x84, 0xc9, 0x76, 0xa8, 0x21, 0x3a,
	0xb3, 0x64, 0x36, 0x88, 0xff, 0x5e, 0xba, 0x6d, 0x04, 0x0f, 0x42, 0x4f, 0xc3, 0x83, 0xc7, 0xe3,
	0x63, 0xe0, 0x3c, 0xf4, 0x12, 0x45, 0xdd, 0x97, 0xf4, 0x1d, 0xf5, 0x65, 0x22, 0x6b, 0x76, 0x94,
	0x5f, 0xc1, 0x51, 0x85, 0x4a, 0xf6, 0x02, 0x8c, 0x47, 0xa5, 0xa7, 0xe5, 0x74, 0x72, 0x3d, 0x99,
	0x1f, 0xd7, 0x7b, 0xca, 0x67, 0x90, 0xd5, 0xa4, 0x41, 0x58, 0xc9, 0x4e, 0xe1, 0xe4, 0x79, 0xf0,
	0x9e, 0x54, 0x93, 0x94, 0xd5, 0x23, 0xe6, 0x33, 0x80, 0x6d, 0x65, 0x15, 0xd6, 0x18, 0x53, 0xab,
	0xfa, 0xd3, 0xaa, 0xc6, 0x56, 0xb2, 0x96, 0x14, 0xb1, 0xfd, 0xf8, 0xcf, 0xba, 0x7d, 0x03, 0xf3,
	0x92, 0xb6, 0xd9, 0x39, 0x98, 0x47, 0xd5, 0x76, 0xc3, 0xf6, 0xb4, 0xdc, 0x8f, 0xdf, 0x3a, 0x97,
	0x67, 0x23, 0xfd, 0x2e, 0xbb, 0x81, 0x6c, 0xc5, 0x78, 0x90, 0xbb, 0x78, 0x78, 0xbd, 0xdf, 0xb4,
	0xf1, 0x7d, 0x68, 0x4a, 0x2f, 0x9f, 0x6e, 0x81, 0x8c, 0x8c, 0x05, 0x4b, 0x81, 0x8c, 0x4e, 0x87,
	0x10, 0xa4, 0x8f, 0x45, 0x6c, 0x7d, 0x47, 0xb1, 0x88, 0xdf, 0x5e, 0x84, 0x5d, 0x83, 0xbe, 0x23,
	0x5e, 0xbb, 0xdd, 0x1f, 0x1b, 0x93, 0xee, 0xdd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xfb,
	0x56, 0x2c, 0x58, 0x01, 0x00, 0x00,
}
